version: '3.3'

services:
  app:
    image: spring-boot-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      - db
    networks:
      - quote-net
    ports:
      - 8080:8080
  db:
    image: postgres:latest
    container_name: "db"
    networks:
      - quote-net
    environment:
      POSTGRES_DB: quote
      POSTGRES_USER: quote
      POSTGRES_PASSWORD: quote
    ports:
      - "5433:5432"
networks:
  quote-net:
    driver: bridge